# base_watcher.py - Template for all watchers
"""
BaseWatcher — Abstract Template for All Watchers
==================================================
Core Watcher Pattern (Perception Layer)

All watchers (Gmail, WhatsApp, Filesystem) inherit from this class.
The Watcher layer is your AI Employee's sensory system. These lightweight
Python scripts run continuously, monitoring various inputs and creating
actionable files for processing.

Subclasses must implement:
    - check_for_updates() -> list  — Return list of new items to process
    - create_action_file(item) -> Path  — Create .md file in Needs_Action

Usage:
    class MyWatcher(BaseWatcher):
        def check_for_updates(self): ...
        def create_action_file(self, item): ...

    watcher = MyWatcher('/path/to/vault')
    watcher.run()
"""

import time
import logging
from pathlib import Path
from abc import ABC, abstractmethod
from datetime import datetime, timezone

try:
    from Agents.config import VAULT_ROOT, NEEDS_ACTION_DIR, DRY_RUN, now_iso, now_local_iso
    from Agents.action_logger import log_action
except ImportError:
    from config import VAULT_ROOT, NEEDS_ACTION_DIR, DRY_RUN, now_iso, now_local_iso
    from action_logger import log_action


class BaseWatcher(ABC):
    """
    Abstract base class for all watchers.

    Follows the Perception → Reasoning → Action architecture:
    - Perception: check_for_updates() detects new items
    - Handoff: create_action_file() writes .md to /Needs_Action for Claude
    """

    def __init__(self, vault_path: str = None, check_interval: int = 60):
        self.vault_path = Path(vault_path) if vault_path else VAULT_ROOT
        self.needs_action = self.vault_path / 'Needs_Action'
        self.needs_action.mkdir(parents=True, exist_ok=True)
        self.check_interval = check_interval
        self.logger = logging.getLogger(self.__class__.__name__)

    @abstractmethod
    def check_for_updates(self) -> list:
        """
        Return list of new items to process.
        Each item should be a dict with at least:
            - 'title': str
            - 'body': str (or 'snippet')
            - 'source': str (email address, phone number, etc.)
            - 'priority': str ('urgent', 'normal', 'low')
        """
        pass

    @abstractmethod
    def create_action_file(self, item) -> Path:
        """
        Create .md file in Needs_Action folder for a detected item.
        Returns the path to the created file.
        """
        pass

    def setup(self) -> None:
        """Optional setup hook — override for auth, browser launch, etc."""
        pass

    def teardown(self) -> None:
        """Optional cleanup hook — override for closing connections."""
        pass

    # ------------------------------------------------------------------
    # Default create_action_file for simple items
    # ------------------------------------------------------------------

    def _default_create_action_file(self, item: dict) -> Path:
        """
        Default implementation: write a .md file to /Needs_Action/
        for a detected item with YAML frontmatter.
        """
        ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S")
        safe_title = "".join(
            c if c.isalnum() or c in " _-" else "_"
            for c in str(item.get("title", "untitled"))
        )[:60].strip()

        watcher_name = self.__class__.__name__.lower()
        filename = f"{ts}_{watcher_name}_{safe_title}.md"
        filepath = self.needs_action / filename

        priority = item.get("priority", "normal")
        priority_icon = {"urgent": "🔴", "normal": "🟡", "low": "🟢"}.get(priority, "⚪")

        content = f"""---
type: {item.get('type', 'task')}
from: {item.get('source', 'Unknown')}
subject: {item.get('title', 'No Subject')}
received: {now_iso()}
priority: {priority}
status: pending
---

# {priority_icon} {item.get('title', 'Untitled')}

**From:** {item.get('source', 'unknown')}
**Detected by:** {watcher_name}
**Time:** {now_local_iso()}

---

## Content

{item.get('body', item.get('snippet', '(no content)'))}

---

## Suggested Actions
- [ ] Review content
- [ ] Take appropriate action
- [ ] Archive after processing

---

> *Auto-generated by {watcher_name}*
"""
        filepath.write_text(content, encoding="utf-8")

        log_action(
            action_type="watcher_detection",
            actor=watcher_name,
            target=filename,
            description=f"Detected: {item.get('title', 'untitled')} from {item.get('source', 'unknown')}",
            status="success" if not DRY_RUN else "dry_run",
        )

        return filepath

    # ------------------------------------------------------------------
    # Run methods
    # ------------------------------------------------------------------

    def run_once(self) -> list[Path]:
        """Execute a single poll cycle and create action files."""
        items = self.check_for_updates()
        created = []
        for item in items:
            path = self.create_action_file(item)
            watcher_name = self.__class__.__name__
            print(f"  📥  [{watcher_name}] {item.get('title', '?')} → {path.name}")
            created.append(path)
        if not items:
            print(f"  ✅  [{self.__class__.__name__}] No new items.")
        return created

    def run(self):
        """
        Continuously poll for updates — the standard entry point.
        Runs until interrupted. Wakes up immediately when machine starts.
        """
        watcher_name = self.__class__.__name__
        self.logger.info(f'Starting {watcher_name}')
        print(f"👁️  {watcher_name} started — polling every {self.check_interval}s")
        print(f"    Dry-run: {DRY_RUN}  |  Press Ctrl+C to stop\n")

        self.setup()
        try:
            while True:
                try:
                    items = self.check_for_updates()
                    for item in items:
                        path = self.create_action_file(item)
                        print(f"  📥  [{watcher_name}] {item.get('title', '?')} → {path.name}")
                except Exception as e:
                    self.logger.error(f'Error: {e}')
                    log_action(
                        action_type="watcher_error",
                        actor=watcher_name.lower(),
                        target="poll",
                        description=str(e),
                        status="failed",
                    )
                    print(f"  ⚠️  [{watcher_name}] Error: {e}")
                time.sleep(self.check_interval)
        except KeyboardInterrupt:
            print(f"\n🛑  {watcher_name} stopped by user.")
        finally:
            self.teardown()

    # Backward-compat alias
    watch_loop = run
